id: obnb
name: 260719-obnb-upgrade-fab-kit
created: 2026-07-19T15:14:41Z
created_by: Sahil Ahuja
change_type: chore
issues: []
progress:
    intake: done
    apply: done
    review: done
    hydrate: done
    ship: done
    review-pr: active
plan:
    generated: true
    task_count: 5
    acceptance_count: 6
    acceptance_completed: 6
confidence:
    certain: 4
    confident: 0
    tentative: 0
    unresolved: 0
    score: 5.0
    fuzzy: true
    dimensions:
        signal: 81.3
        reversibility: 88.8
        competence: 91.3
        disambiguation: 86.3
stage_metrics:
    intake: {started_at: "2026-07-19T15:14:41Z", driver: fab-new, iterations: 1, completed_at: "2026-07-19T15:16:15Z"}
    apply: {started_at: "2026-07-19T15:16:15Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-19T15:18:39Z"}
    review: {started_at: "2026-07-19T15:18:39Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-19T15:24:17Z"}
    hydrate: {started_at: "2026-07-19T15:24:17Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-19T15:25:25Z"}
    ship: {started_at: "2026-07-19T15:25:25Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-19T15:27:15Z"}
    review-pr: {started_at: "2026-07-19T15:27:15Z", driver: git-pr, iterations: 1}
prs:
    - https://github.com/sahil87/hop/pull/58
change_type_source: explicit
true_impact:
    added: 269
    deleted: 3
    net: 266
    excluding:
        added: 0
        deleted: 0
        net: 0
    tests:
        added: 0
        deleted: 0
        net: 0
    computed_at: "2026-07-19T15:27:15Z"
    computed_at_stage: ship
# true_impact: lazily created on first stage-finish that computes it (no placeholder here).
last_updated: 2026-07-19T15:27:15Z
