id: n1me
name: 260602-n1me-config-add-rm-folders
created: 2026-06-02T18:40:00Z
created_by: sahil87
change_type: refactor
issues: []
progress:
    intake: done
    apply: done
    review: done
    hydrate: done
    ship: done
    review-pr: active
plan:
    generated: true
    task_count: 11
    acceptance_count: 21
    acceptance_completed: 21
confidence:
    certain: 10
    confident: 2
    tentative: 0
    unresolved: 0
    score: 4.4
    fuzzy: true
    dimensions:
        signal: 88.8
        reversibility: 83.8
        competence: 88.3
        disambiguation: 87.1
stage_metrics:
    intake: {started_at: "2026-06-02T18:40:00Z", driver: fab-new, iterations: 1, completed_at: "2026-06-02T19:08:43Z"}
    apply: {started_at: "2026-06-02T19:24:14Z", driver: fab-fff, iterations: 2, completed_at: "2026-06-02T19:26:28Z"}
    review: {started_at: "2026-06-02T19:26:28Z", driver: fab-fff, iterations: 1, completed_at: "2026-06-02T19:27:52Z"}
    hydrate: {started_at: "2026-06-02T19:27:52Z", driver: fab-fff, iterations: 1, completed_at: "2026-06-02T19:32:32Z"}
    ship: {started_at: "2026-06-02T19:32:32Z", driver: fab-fff, iterations: 1, completed_at: "2026-06-02T19:34:13Z"}
    review-pr: {started_at: "2026-06-02T19:34:13Z", driver: git-pr, iterations: 1}
prs:
    - https://github.com/sahil87/hop/pull/29
true_impact:
    added: 0
    deleted: 0
    net: 0
    excluding:
        added: 0
        deleted: 0
        net: 0
    computed_at: "2026-06-02T19:32:32Z"
    computed_at_stage: hydrate
# true_impact: lazily created on first apply-finish (no placeholder here).
last_updated: 2026-06-02T19:34:13Z
